language: node_js
node_js:
  - "10.14.2"

cache: npm

script:
  - npm run build

before_install:
  - openssl aes-256-cbc -K $encrypted_3fe0369f6901_key -iv $encrypted_3fe0369f6901_iv
    -in myserver.pem.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

after_success:
  - pwd
  - ls
  - scp -o stricthostkeychecking=no -r dist/* centos@ichris.info:/opt/service/web/www/
  - ssh centos@ichris.info "pwd"

addons:
  ssh_known_hosts: ichris.info

notifications:
  email:
    recipients:
    - chrislu.name@gmail.com
    on_success: always
    on_failure: always
